# Hugo build configuration for Netlify
# (https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify)

[build]
command = "npm build:preview"

[build.environment]
GO_VERSION = "1.20.4"

[context.production]
command = "npm build:production"
