name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: ls -a via ssh
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd /tmp
          ls -a
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USER }}
        key: ${{ secrets.ACTIONS}}
